# Generated by Django 5.0.6 on 2024-07-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w84u', '0003_marker_markerhistory_match_message_delete_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
