# Generated by Django 5.0.6 on 2024-07-30 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w84u', '0008_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='data_range_begin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='session',
            name='data_range_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], default='пол', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='session_images/'),
        ),
        migrations.AddField(
            model_name='session',
            name='more_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(default='имя', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='time_range_begin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='time_range_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
