# Generated by Django 5.0.6 on 2024-07-31 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w84u', '0009_session_data_session_data_range_begin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='data_range_begin',
            new_name='date_range_begin',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='data_range_end',
            new_name='date_range_end',
        ),
    ]
