# Generated by Django 5.0.6 on 2024-08-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w84u', '0010_rename_data_session_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date_range_begin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
