# Generated by Django 5.0.6 on 2024-08-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w84u', '0011_alter_session_date_range_begin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
