# Generated by Django 5.0.6 on 2024-08-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w84u', '0015_optionalinfo_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
