# Generated by Django 5.0.6 on 2024-08-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w84u', '0016_session_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
