# Generated by Django 5.0.6 on 2024-08-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w84u', '0017_alter_session_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_range_begin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_range_end',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
