# Generated by Django 5.0.6 on 2024-08-07 11:37

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w84u', '0018_alter_session_time_alter_session_time_range_begin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='date_range_begin',
        ),
        migrations.RemoveField(
            model_name='session',
            name='date_range_end',
        ),
        migrations.RemoveField(
            model_name='session',
            name='time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='time_range_begin',
        ),
        migrations.RemoveField(
            model_name='session',
            name='time_range_end',
        ),
        migrations.AddField(
            model_name='session',
            name='datetime_range',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True),
        ),
    ]
