# Generated by Django 5.0.6 on 2024-08-07 23:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w84u', '0019_remove_session_date_range_begin_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marker',
            unique_together={('user', 'type')},
        ),
        migrations.AddField(
            model_name='marker',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='marker',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='longitude',
        ),
    ]
