# Generated by Django 5.0.6 on 2024-08-08 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w84u', '0020_alter_marker_unique_together_marker_location_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marker',
            unique_together=set(),
        ),
    ]
