# Generated by Django 5.0.6 on 2024-09-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w84u', '0024_alter_match_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
