"""init

Revision ID: dd3864701751
Revises: e48bdac774f0
Create Date: 2024-07-16 21:22:09.698738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd3864701751'
down_revision: Union[str, None] = 'e48bdac774f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('type', sa.Enum('red', 'blue', name='type'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name=op.f('fk_marker_user_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marker'))
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_1', sa.Integer(), nullable=True),
    sa.Column('user_2', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_1'], ['users.id'], name=op.f('fk_match_user_1_users')),
    sa.ForeignKeyConstraint(['user_2'], ['users.id'], name=op.f('fk_match_user_2_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match'))
    )
    op.create_table('markerhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('marker', sa.Integer(), nullable=True),
    sa.Column('match', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['marker'], ['marker.id'], name=op.f('fk_markerhistory_marker_marker')),
    sa.ForeignKeyConstraint(['match'], ['match.id'], name=op.f('fk_markerhistory_match_match')),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name=op.f('fk_markerhistory_user_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_markerhistory'))
    )
    op.create_table('messsage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match', sa.Integer(), nullable=True),
    sa.Column('sender', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('read', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match'], ['match.id'], name=op.f('fk_messsage_match_match')),
    sa.ForeignKeyConstraint(['sender'], ['users.id'], name=op.f('fk_messsage_sender_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messsage'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messsage')
    op.drop_table('markerhistory')
    op.drop_table('match')
    op.drop_table('marker')
    # ### end Alembic commands ###
